### ISSUE TITLE
Logging should be optional

### ISSUE THREAD

**Issue by trendy-weshy** [ketanTechracers/schema-validator#1]
I have a request, can we have the logging as optional or add an optional `level` lets say, `verbose`, `warn` and `error`.

It would help reduce the amount of logs on the terminal.

**Comment by Vonor** [comment]
+1 for this. "none", "verbose", "warn" and "error" sound good.

additionally add a return false in case of a non successful validation so that something like this is possible:
```javascript
if (validateSchema()) {
  // do stuff on success
} else {
  // do something else
}
```

**Comment by ketanTechracers** [comment]
@Vonor Thanks for the feature suggestion! Done in https://github.com/ketanTechracers/schema-validator/pull/5 . Closing this Issue!
